name: boring_to_beautiful
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adaptive_breakpoints: ^0.1.4
  adaptive_components: ^0.0.7
  adaptive_navigation: ^0.0.7
  animations: ^2.0.7
  collection: ^1.16.0
  desktop_window: ^0.4.0
  dynamic_color: ^1.5.4
  english_words: ^4.0.0

  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  material_color_utilities:
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/playlists/
  - assets/images/albums/
  - assets/images/artists/
  - assets/images/news/
